title: Shift Collective - Docs
description: Public documentation by the Shift Collective
theme: just-the-docs

url: https://shiftcollective-org.github.io/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
